name: DevSecOps Assignment
on:
  push:
    branches: [ "main" ]

jobs:
  devsecops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/analyze@v3
      - run: pip install bandit
      - run: bandit -r api --severity-level high
      - run: pip install safety
      - run: safety check -r requirements.txt
      - run: docker build -t assignment-api .
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: assignment-api
          severity: CRITICAL,HIGH
          exit-code: 1
